# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7bd618bb00933fa7d1f42b5bf257d3917527797da73e3a8ff1f6cf2ce25428cbc9f4fe1e91fe83c4a921a74bf42c3b00dbaf76347fa88283900ebcd7212385

test:
  secret_key_base: c3849c7573226dfbed1ba5a642502b2aec9f94292c1461b07ad58fb2924c703ca8b8b5998667e557133173bb0b80d7bec03fc78140ef4ad1c59c9ef7d3cd16ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
